name: sahamuas
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # atau ">=3.0.0 <4.0.0" jika Anda menggunakan Dart 3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  get: ^4.6.5
  fl_chart: ^0.65.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.10
  shared_preferences: ^2.0.8
  loading_animation_widget: ^1.2.0+4
  permission_handler: ^10.0.0
  firebase_core: any
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  cloud_firestore: ^4.8.2
  fluttertoast: ^8.2.6
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/logo_nobg.png
  uses-material-design: true
